# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[roles.technical-lead]
role-name = "Technical Lead"
name = "Pietro Albini"
email = "pietro.albini@ferrous-systems.com"
