# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

---

name: Release
on:
  # Run nightly releases every day at midnight UTC.
  schedule:
    - cron: "0 0 * * *"

  # Allow team members to manually trigger new releases through the GitHub UI.
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to release
        required: true
      env:
        description: Environment to perform the release in
        type: choice
        required: true
        options:
          - dev
          - prod
      override-existing:
        description: Allow overriding existing releases
        type: boolean
      allow-duplicate:
        description: Allow duplicate releases
        type: boolean


permissions:
  # Allow read access to the source code
  contents: read
  # Allow obtaining the OIDC token required for AWS authentication.
  id-token: write

jobs:
  scheduler:
    name: Scheduler
    runs-on: ubuntu-latest
    environment: release-scheduler
    outputs:
      jobs: ${{ steps.jobs.outputs.jobs }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-requests python3-boto3

      - name: Load AWS credentials into the environment
        run: ferrocene/ci/scripts/assume-aws-oidc-role.sh
        env:
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}

      - name: Calculate the release job matrix
        run: ferrocene/ci/scripts/calculate-release-job-matrix.py >> $GITHUB_OUTPUT
        id: jobs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [scheduler]
    strategy:
      matrix:
        include: ${{ fromJSON(needs.scheduler.outputs.jobs) }}
      fail-fast: false
      max-parallel: 1

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Load AWS credentials into the environment
        run: ferrocene/ci/scripts/assume-aws-oidc-role.sh
        env:
          AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}

      - name: Run the release process
        run: ${{ matrix.command }}
        env:
          PUBLISHRELEASE_ARTIFACTS_ROLE: ${{ vars.PUBLISHRELEASE_ARTIFACTS_ROLE }}
          PUBLISHRELEASE_ARTIFACTS_BUCKET: ${{ vars.PUBLISHRELEASE_ARTIFACTS_BUCKET }}
          PUBLISHRELEASE_DOCS_BUCKET: ${{ vars.PUBLISHRELEASE_DOCS_BUCKET }}
          PUBLISHRELEASE_RELEASES_BUCKET: ${{ vars.PUBLISHRELEASE_RELEASES_BUCKET }}
          PUBLISHRELEASE_SIGNING_KEY_ARN: ${{ vars.PUBLISHRELEASE_SIGNING_KEY_ARN }}
          AWS_REGION: eu-central-1
